services:
  db:
    restart: always
    image: mariadb:11.6.2
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=restaurant_db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=<password>
      - MYSQL_ROOT_PASSWORD=<root_password>
    ports:
      - "3306:3306"
    networks:
      - db-net
    volumes:
      - db_data:/var/lib/mysql

  backend:
    restart: always
    container_name: backend
    command : sh -c "python manage.py makemigrations &&
                      python manage.py migrate &&
                      python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./backend/.env
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - db-net

  frontend:
    restart: always
    command : http-server dist -p 3000
    container_name: frontend
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - db-net

networks:
  db-net:
    driver: bridge

volumes:
  db_data: