# # docker-compose.yml

# version: '3'

# services:
#   backend:
#     build:
#       context: ./backend
#     container_name: django-backend
#     command: python manage.py runserver 0.0.0.0:8000
#     volumes:
#       - ./backend:/app
#     ports:
#       - "8000:8000"
#     environment:
#       - DB_ENGINE=sqlite3
#       - DB_NAME=db.sqlite3
#     depends_on:
#       - frontend

#   frontend:
#     build:
#       context: ./frontend
#     container_name: react-frontend
#     volumes:
#       - ./frontend:/app
#     ports:
#       - "3000:3000"
#     environment:
#       - REACT_APP_BACKEND_URL=http://localhost:8000/api
#     command: npm start
version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: admin
      MYSQL_PASSWORD: adminpassword
      MYSQL_DATABASE: restaurant
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:

volumes:
  mysql_data:

