# docker-compose.yml

version: '3'

services:
  backend:
    build:
      context: ./backend
    container_name: django-backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DB_ENGINE=sqlite3
      - DB_NAME=db.sqlite3
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend
    container_name: react-frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8000/api
    command: npm start
